import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-quran',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './quran.component.html',
  styleUrl: './quran.component.css'
})
export class QuranComponent {
  constructor(private router: Router){ }

  surah_lists = [
    { surahNumber: 1, suranameEng: 'Al Fatiha', suranameArabic: 'اَلْفَاتِحَة', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Fatiha' },
    { surahNumber: 2, suranameEng: 'Al Baqarah', suranameArabic: 'اَلْبَقَرَة', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Baqarah' },
    { surahNumber: 3, suranameEng: 'Al Imran', suranameArabic: 'اٰلِ عِمْرَان', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Imran' },
    { surahNumber: 4, suranameEng: 'An Nisa', suranameArabic: 'اَلنِّسَآء', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'An Nisa' },
    { surahNumber: 5, suranameEng: 'Al Maidah', suranameArabic: 'اَلْمَـآئِدَة', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Maidah' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 7, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 8, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 9, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 10, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 11, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 12, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 13, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 14, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 15, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 16, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 17, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 18, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },
    { surahNumber: 6, suranameEng: 'Al Anam', suranameArabic: 'اَلْاَ نْعَام', imgSrc: 'assets/img/quran/makkah-img.ico', imgAlt: 'Al Anam' },

  ];
   para_lists = [
    { paraNumber: 1, paraName: 'الٓمّٓ' },
    { paraNumber: 2, paraName: 'سَیَقُوْلُ' },
    { paraNumber: 3, paraName: 'تِلْكَ الرُّسُلُ' },
    { paraNumber: 4, paraName: 'لَنْ تَنَالُوا' },
    { paraNumber: 5, paraName: 'وَالْمُحْصَنَاتُ' },
    { paraNumber: 6, paraName: 'يَا أَيُّهَا الَّذِينَ' },
    { paraNumber: 7, paraName: 'وَإِذَا سَمِعُوا' },
    { paraNumber: 8, paraName: 'قَالَ الْمَلَأُ' },
    { paraNumber: 9, paraName: 'قَدْ أَفْلَحَ' },
    { paraNumber: 10, paraName: 'وَاعْلَمُوا' },
    { paraNumber: 11, paraName: 'يَعْتَذِرُونَ' },
    { paraNumber: 12, paraName: 'وَمَا مِنْ دَآبَّةٍ' },
    { paraNumber: 13, paraName: 'وَمَاۤ اُبَرِّئُ' },
    { paraNumber: 14, paraName: 'رُبَمَا' },
    { paraNumber: 15, paraName: 'سُبْحَانَ الَّذِي' },
    { paraNumber: 16, paraName: 'قَالَ أَلَمْ' },
    { paraNumber: 17, paraName: 'اقْتَرَبَ لِلْنَّاسِ' },
    { paraNumber: 18, paraName: 'قَدْ أَفْلَحَ' },
    { paraNumber: 19, paraName: 'وَقَالَ الَّذِينَ' },
    { paraNumber: 20, paraName: 'أَمَّنْ خَلَقَ' },
    { paraNumber: 21, paraName: 'اتْلُ مَا أُوحِيَ' },
    { paraNumber: 22, paraName: 'وَمَنْ يَقْنُتْ' },
    { paraNumber: 23, paraName: 'وَمَا أُنْزِلَ إِلَيْكُم' },
    { paraNumber: 24, paraName: 'فَمَنْ أَظْلَمُ' },
    { paraNumber: 25, paraName: 'إِلَيْهِ يُرَدُّ' },
    { paraNumber: 26, paraName: 'حٰمٓ' },
    { paraNumber: 27, paraName: 'قَالَ فَمَا خَطْبُكُم' },
    { paraNumber: 28, paraName: 'قَدْ أَفْلَحَ' },
    { paraNumber: 29, paraName: 'بَارَكَ الَّذِي' },
    { paraNumber: 30, paraName: 'عَمَّ یَتَسَاءَلُوْنَ' }
];



  quranDetails()
  {
     this.router.navigate(['/quran-details']);
  }
}
